### ISSUE TITLE
Language box underneath Content editing

### ISSUE THREAD

**Issue by paaljoachim** [nikolov-tmw/multilingual-wp#41] opened 2014-02-13 16:29 UTC
Hey I noticed your thoughts on side-by-side editing....

What about editing a language underneath the content editing box? One can see the original on top and another language below. Easily switching between the two as both are open and seen at the same time.

**Comment by nikolov-tmw** [comment] 2014-02-13 17:11
The goal I think would be to have a configurable amount of columns - so you can have 1 column, 2 columns, etc. And then you can drag-and-drop the language boxes around. 

So this way what you described would be possible.

**Comment by nikolov-tmw** [comment] 2014-02-13 17:13
Thanks for the input, but I'll close the issue as a duplicate of #30 - since I've described the option for number of columns control.

**Closed as completed by nikolov-tmw** 2014-02-13 17:13 UTC
Labels: bug
